zeromq/zmqpp

AUTHORS, src/tests/test_auth.cpp, src/zmqpp/auth.cpp, src/zmqpp/auth.hpp, src/zmqpp/message.cpp, src/zmqpp/message.hpp, src/zmqpp/socket_options.hpp, src/zmqpp/zap_request.cpp, src/zmqpp/zap_request.hpp
Add a wrapper around `zmq_msg_gets()`. This is the `message::get_property()` method.
Modify the current ZAP module to populate the `user-id` when available:
+ with PLAIN by using the username.
+ with CURVE by using the client's public key.
Drop support of ZMQ_IDENTITY_FD.
=> Zap improv

src/client/main.cpp, src/client/options.cpp
Hello,
These changes were needed to compile zmqpp-client on a Mac running OS X 10.10. zmqpp was configured using the CMake scripts and compiled with Xcode 6.1.
=> Compilation fix for zmqpp-client on Mac OS X 10.10

AUTHORS, src/client/main.cpp
Using some cross-compiling toolchains, EXIT_FAILURE is not always
properly defined without this inclusion.
Add myself to AUTHORS.
Signed-off-by: Lionel Orry <lionel.orry@gmail.com>
=> add cstdlib header to ensure EXIT_FAILURE presence

src/zmqpp/auth.cpp, src/zmqpp/auth.hpp, src/zmqpp/compatibility.hpp
A new define ZMQPP_NO_CONSTEXPR was introduced in compatibility.h. It is
set for all versions of VC++ including VC2013. VC2015 should have
support for constexpr but needs to be tested when it is available.
This fixes #99.
=> VC2013 compile fix (no support for constexpr).

src/zmqpp/compatibility.hpp, src/zmqpp/poller.cpp, src/zmqpp/poller.hpp, src/zmqpp/reactor.cpp, src/zmqpp/reactor.hpp
Until now adding raw sockets to poller and reactor was done using a file
descriptor as an int. This only works properly under POSIX. Under Windows
a raw socket is represented as a SOCKET type. This type cannot simply be
cast into int because under 32-bit it is actually an unsigned int and
under 64-bit it is an unsigned __int64.
The problem was solved by introducing a new typedef raw_socket_t which
is of type SOCKET under Windows and an int under the other platforms.
All methods taking an int as a file descriptor now take raw_socket_t
hiding this platform detail away.
The documention was changed accordingly to talk about 'standard socket'
where 'file descriptor' was used before.
This is a api-breaking change (at least under Windows).
This fixes #111.
=> Improved the api dealing with file descriptors (see  #111).

src/zmqpp/poller.cpp
The three variants of add() and remove() in poller where used duplicated
code. Now the versions takeing a socket or a raw_sokcket simply call the
third version taking a zmq_pollitem_t.
This fixes #15.
=> Removed code duplication in poller.

src/zmqpp/poller.cpp, src/zmqpp/poller.hpp
* poller::add(zmq_pollitem_t) takes a const reference just like the other methods
* poller declares const references as "foo const&" consistently now
=> Fixed some api inconsistencies.

src/zmqpp/actor.cpp, src/zmqpp/auth.cpp, src/zmqpp/message.cpp, src/zmqpp/socket.cpp
Converted two while(true) loops into for(;;) in order to avoid:
"warning C4127: conditional expression is constant".
Removed the variable name from two catch blocks to avoid:
"warning C4101: 'e' : unreferenced local variable".
=> Silenced some VC++ compiler warnings.

src/tests/test_sanity.cpp
This fixes #116.
Problem: The creation of the zmq_pollitem_t object
had a typo, resulting in a call to zmq_poll() that didn't
really make sense.
Solution: Correctly create the pollitem and adjust the BOOT_CHECK
call to a proper expected result. Also increase the max timeout
to 1second to make sure the message as plenty of time to be
delivered.
=> Fix error in test.

CHANGES.md, Doxyfile, Makefile, src/mainpage.md, src/zmqpp/auth.hpp, src/zmqpp/context.hpp, src/zmqpp/curve.hpp, src/zmqpp/exception.hpp, src/zmqpp/message.hpp, src/zmqpp/poller.hpp, src/zmqpp/reactor.hpp, src/zmqpp/socket.hpp, src/zmqpp/z85.hpp, src/zmqpp/zap_request.hpp
This adds a mainpage to doxygen documentation (i'll just go ahead and implement #69 when this is merged).
I also bump the version to 4.1.2 so I can tag a release, as promised in #118.
Ps: Sorry about #121 , I forced pushed my branch to fix and that prevents me from reopening the PR, hence this new one.
=> Documentation improvement + switch to 4.1.2

src/tests/test_message.cpp, src/zmqpp/compatibility.hpp, src/zmqpp/message.hpp
See #123. The NoCopy mechanism was available through `move()`
and `add_const()`.
This patch adds `add_nocopy()` and `add_nocopy_const()`.
`add_nocopy()` is similar to `move()` but does not perform
memory allocation to create a type safe deleter. Instead the
user provide his own libzmq-level deleter. Reject pointer to
const data.
`add_nocopy_const()` let the user pass a pointer to const data
and perform the cast internally. This function is to make it
very clear that the user pass const data and that he must
therefore be careful not modifying them later.
Deprecate `add_const()` in favor of the new functions (see #123
for more info).
=> Problem: No Copy behavior could be improved.

src/zmqpp/socket.cpp
I tried setting `socket.set(zmqpp::socket_option::router_handover, true);` but was getting a runtime exception that it could not be done.
```
terminate called after throwing an instance of 'zmqpp::exception'
what():  attempting to set a non boolean option with a boolean value
Aborted (core dumped)
```
I added the above snippet so that now zmqpp correctly handles this call.
I tested the solution manually and it works as intended. Also, I tried to write a unit test, but I could not get my hand around all those macros -- I am rather new to C++. 
I also considered writing a corresponding fix for the get option, but [according to the docs](http://zeromq.github.io/zmqpp/namespacezmqpp.html#aea04ff9a72915eb7fc621a023f3e8843), this should be a _set only_ option.
=> Added socket option for router_handover

src/zmqpp/actor.cpp, src/zmqpp/actor.hpp
The first commit is simply a reformatting to replace tabs by space and uniform this.
The second commit allows exceptions to propagate from actor thread to parent thread during actor initialization.
=> Improve exception handling

CMakeLists.txt, src/tests/test_proxy.cpp, src/zmqpp/proxy.cpp, src/zmqpp/proxy.hpp
Zmqpp didn't provide a wrapper around `zmq_proxy`. See #129 .
(This does not bring support to `zmq_proxy_steerable`)
=> Problem: No wrapper for zmq_proxy

src/zmqpp/socket.cpp
A ::send() marked unblocking, where the zmq[_send,_sendmsg,_ms_send]
of the first (or only) part returned EINTR was expected to
return FALSE (== would-block) to the caller, but instead would
have sent the entire message. The comments indicate that this
could lead to the send blocking.
This would not be visible in our code, apart from a failure to update
statistics about blocked sends. These statistics are used to infer
which parts of the processing pipeline is slow, and are not critical.
The bug was found by code inspection and no testcase has been written.
=> Fix a low probability bug in ::send()

src/zmqpp/inet.hpp
We cannot use inet.hpp on its own because it is missing some includes.
=> Problem: Cannot use inet.hpp on its own

Makefile
Problem: Since `libsodium/master` defaulted to `tweetnacl` for CURVE, the use of `libsodium` became optional. However, `Makefile` of this project still links to `libsodium`, which breaks the build of this bindings on a machine that does not have `libsodium` installed.
(Moreover, it appears that the link was redundant, since building `libzmq` with `libsodium` still succeeds.)
=> Removes libsodim dependency from tests

src/zmqpp/socket.cpp
When reading a string value from zmq_getsockopt, it includes the terminating NUL character in the size. Which is reasonable since it's advertised as a buffer size. But when zmqpp turns that into a C++ string, the terminating null is inappropriate. This patch removes the terminating NUL.
=> Avoid terminating NUL in socket::get(..., string&)

CMakeLists.txt, src/tests/test_sanity.cpp, src/zmqpp/compatibility.hpp, src/zmqpp/context.hpp, src/zmqpp/exception.hpp, src/zmqpp/frame.hpp, src/zmqpp/message.hpp, src/zmqpp/poller.cpp, src/zmqpp/poller.hpp, src/zmqpp/signal.hpp, src/zmqpp/socket.cpp, src/zmqpp/socket.hpp, src/zmqpp/zmqpp.hpp
- const static variables moved from source to header
- export header generated by cmake
=> Export several classes in Windows

src/tests/test_auth.cpp, src/zmqpp/zap_request.cpp, src/zmqpp/zap_request.hpp
Solution: Update `zap_request::reply` method to take an optional argument
containing metadata name-value pairs of type string and serialize them to
wireformat specified in ZRFC 27.
=> Problem: Metadata in ZAP responses is unused

src/zmqpp/socket.cpp, src/zmqpp/socket.hpp
To resolved #58 there is a new bool version of the string send and receive message functions, and the previous integer versions have been marked as deprecated in favour of the Message class version.
Anyone using the default values for both send and receive previously is unaffected as the default for the boolean is identical.
Anyone overriding the send default to send multipart messages and using the default receive has been accounted for by only pulling one part off the socket at a time. As the new send is only single part this doesn't pose a problem moving forward.
Anyone overriding both defaults is still using the deprecated functions and so unaffected.
=> moving to bool as default type, keeping depreacted int fallback

src/tests/test_socket_options.cpp, src/zmqpp/socket.cpp, src/zmqpp/socket_options.hpp
This simple patch exposes the new ZMQ_USE_FD socket option of the upcoming zmq 4.2. This option is listed among experimental options ("draft"), but it was implemented already in February (https://github.com/zeromq/libzmq/commit/4bcbb3055ebf6753a2135fb3132311603d6ea930 and then renamed) so hopefuly it won't undergo any significant changes.
The support for this option is needed for the project I'm working on (scopes API in Ubuntu) and it would be great if it was accepted into the  zmqpp.
=> Support for ZMQ_USE_FD (available in zmq master for upcoming zmq 4.2)

CMakeLists.txt
This changes the edits in benjamg-patch-1 to conditionally use `-Wextra` if we aren't compiling on MSVC.
=> Use -Wextra on compilers that aren't MSVC

CMakeLists.txt, src/zmqpp/byte_ordering.hpp, src/zmqpp/zap_request.cpp
This change eliminates the call to `htobe32` which broke builds on OS X causing #164 and broke builds on Windows and possibly being related to #144. 
Endian byte ordering is moved to `byte_ordering.hpp` and defines a macro based on the platform being used. I only implemented host to big endian for 32 bits since that is the only call that seems to be used in the source code. Other conversions can be implemented if (or when) needed.
=> Cross platform endian conversions

src/tests/test_socket.cpp, src/zmqpp/socket.cpp
The receive_raw function is passed the maximum size of the buffer in the
length parameter.  The documentation states that the function will write
no more than this number of bytes.  Make sure that this is the case.
Also, add a test case that tests this.
=> Respect the passed in length to socket::receive_raw

src/tests/test_socket.cpp, src/zmqpp/socket.cpp, src/zmqpp/socket.hpp
Sockets can be unmonitored. This is not mentioned in documentation (which is pretty unclear), but the feature is implemented (https://github.com/zeromq/libzmq/blob/master/src/socket_base.cpp#L1592).
This merge add:
- the function zmqpp::socket::unmonitor,
- the event zmqpp::event::monitor_stopped (which is sent when unmonitor is called),
- test for unmonitor in test_socket.cpp.
=> Add function unmonitor to zmqpp::socket

src/zmqpp/zap_request.cpp
This change eliminates the inclusion of "netinet/in.h" on Windows, which does not exist on that platform. The inclusion of that file breaks Windows builds. I did not need to include "winsock2.h" to get a successful build.
=> This change eliminates the inclusion of "netinet/in.h" on Windows

src/zmqpp/message.hpp
According to current implementation, template method message::get(size_t) can be const method since the method change nothing in the object itself.
This patch just changes current template method to const and user can call the method for const zmqpp::message objects.
=> change template method message::get(n) to const

AUTHORS, CMakeLists.txt, src/tests/test_loop.cpp, src/zmqpp/loop.cpp, src/zmqpp/loop.hpp, src/zmqpp/zmqpp.hpp
Hello, I'm big fan of zloop class in CZMQ project.
I started using reactor class but lack of timer functions was very inconvenient. It was hard to decide whether I should extend reactor class or add a new one. Finally, I decided to add a new one - following pattern in CZMQ project.
If this approach somehow not match your vision, please feel free to comment, it is not that hard to merge them together.
I've noticed that I forgot to put this on separate branch, that is why I closed #186 and opened new PR with separate feature branch.
=> Add loop class based on czmq zloop

src/zmqpp/socket.hpp
send and receive functions will return false if the socket timeout is set and the operation times out.
=> Update documentation of socket send / receive

src/zmqpp/message.hpp
Similar to previous PR #183, template method message::extract() can be const method since the method change nothing in the object itself.
This change allows users to use extract for const message object to fetch part of the message.
=> change template method message::extract() to const

src/zmqpp/frame.hpp
As stated in zmq.h, the zmq_msg_t structure must be aligned on the address boundary if sigbus violations are to be avoided on architectures enforcing the pointer alignment.
=> Flip the order of _msg and _sent in zmq::frame

CHANGES.md, Makefile, src/zmqpp/socket.cpp, src/zmqpp/zmqpp.cpp, src/zmqpp/zmqpp.hpp
Minor fix plus update in prep for  #184 and tagging 4.2
Ideally we should finish the list from that issue but I don't see a nice way to handle things like routing ids which are per part in 0mq but would map to per message here. They should be the same on every part so it might be I'm just over thinking it.
At is stands I think we should tag and export to master at this point.
=> 4.2.0 requirements
